name: smart_bag_controller
description: A mobile app for controlling smart bag with fingerprint authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Bluetooth connectivity
  flutter_blue_plus: ^1.31.15
  # Fingerprint authentication
  local_auth: ^2.1.8
  # State management
  provider: ^6.1.1
  # UI components
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  # Charts for monitoring
  fl_chart: ^0.66.0
  # Local storage
  shared_preferences: ^2.2.2
  # HTTP requests
  http: ^1.1.0
  # Permissions
  permission_handler: ^11.1.0
  # Device info
  device_info_plus: ^9.1.1
  # QR code scanning
  qr_code_scanner: ^1.0.1
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/